server:
  port: 8087

spring:
  application:
    name: wolfie

bot:
  discord:
    token: ???
    guild-id: ???
  front-end:
    url: ???
  evaluation:
    expiration-time: 1d
  roles:
    game-master:
      id: ???
    admin:
      id: ???
  channels:
    commands:
      id: ???
    summary:
      id: ???
    rank-change:
      id: ???
#  join-roles:
#    add:
#      - 0
gemini:
  api-key: ???
  model-name: ???
  pro-model-name: ???
  system-prompt: ???
  knowledge-base-file: ???

logging:
  file:
    name: ./logs/wolfie.log
  charset:
    file: UTF-8
  logback:
    rollingpolicy:
      max-file-size: 5MB
      total-size-cap: 50MB
      max-history: 10
  structured:
    format: 
      file: ecs